name: Generate ASCII Art
on: push
jobs:
  build_job01:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsays
        run: sudo apt install cowsay -y

      - name: Execute ASCII Script
        run: cowsay "MaMa is the Best, MaMa ko Chit Tal" >> mama.txt

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: mama.txt upload
          path: mama.txt

  test_job01:
    needs: build_job01
    runs-on: ubuntu-latest
    steps:
      - name: Donwload File
        uses: actions/download-artifact@v8
        with:
          name: mama.txt download

      - name: Check File Exists
        run: grep -i "MaMa" mama.txt

  deploy_job01:
    needs: test_job01
    runs-on: ubuntu-latest
    steps:
      - name: Donwload File
        uses: actions/download-artifact@v8
        with:
          name: mama.txt download
          
      - name: Read File
        run: cat mama.txt

      - name: Deploy
        run: echo "Deploying........"