name: Generate ASCII Art
on: push
jobs:
    generate_ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: List Repository Files Before Execution
              run: ls -ltra
            - name: Execute ASCII Script For MaMa
              run: |
                chmod +x ascii.sh
                ./ascii.sh